<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 4/19/18
 * Time: 2:42 PM
 */

namespace execut\yii\log;


class EmailTarget extends \yii\log\EmailTarget
{
    public $secondsPeriod = null;
    public function export()
    {
        if (!$this->exportTimeHasCome()) {
            return;
        }

        parent::export(); // TODO: Change the autogenerated stub
    }

    protected function exportTimeHasCome() {
        if ($this->secondsPeriod === null) {
            return true;
        }

        $cacheKey = __CLASS__ . '-' . $this->getExceptionId();
        try {
            $cache = \yii::$app->cache;
            $exportedTime = $cache->get($cacheKey);
            $now = time();
            if ($exportedTime !== false && ($now - $exportedTime) < $this->secondsPeriod) {
                return false;
            }

            $cache->set($cacheKey, $now);
        } catch (\Exception $e) {
        }

        return true;
    }

    protected function getExceptionId() {
        foreach ($this->messages as $message) {
            if (!empty($message[0]) && $message[0] instanceof \Exception) {
                /**
                 * @var \Exception $e ;
                 */
                $e = $message[0];

                return '-' . $e->getFile() . '-' . $e->getLine() . '-' . $e->getMessage();
            } else {
                return '-unknown';
            }
        }
    }
}