<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 4/19/18
 * Time: 2:42 PM
 */

namespace execut\yii\log;


class EmailTarget extends \yii\log\EmailTarget
{
    public $secondsPeriod = null;
    public function export()
    {
        if (!$this->exportTimeHasCome()) {
            return;
        }

        parent::export(); // TODO: Change the autogenerated stub
    }

    protected function exportTimeHasCome() {
        if ($this->secondsPeriod === null) {
            return true;
        }

        try {
            $cache = \yii::$app->cache;
            $exportedTime = $cache->get(__CLASS__);
            $now = time();
            if ($exportedTime !== false && ($now - $exportedTime) < $this->secondsPeriod) {
                return false;
            }

            $cache->set(__CLASS__, $now);
        } catch (\Exception $e) {
        }

        return true;
    }
}