<?php  //[STAMP] 9883f69d48a6b0deb06dcb504d1a0cf1
namespace execut\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait CodeGuyActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
